routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\NewsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin','App\Http\Controllers\AdminController@index');

Auth::routes(['register' => false]);
//Auth::routes();

Route::resource('news', NewsController::class);

Route::resource('articles', ArticleController::class);
// Route for get articles for yajra post request.
Route::get('get-articles', [ArticleController::class, 'getArticles'])->name('get-articles');
Route::get('get-news', [NewsController::class, 'getNews'])->name('get-news');

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;

    protected $table = 'news';
    protected $guarded = array();

    public function getData()
    {
        return static::orderBy('created_at','desc')->get();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'userName','email', 'homepage' , 'text' , 'browserInfo', 'IP',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.news.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required',
            'text'  => 'required',
        ]);

        $request['homepage'] = isset( $request['homepage']) ? $request['homepage'] : " ";

        if (strpos($_SERVER['HTTP_USER_AGENT'], 'Chrome'))
        {
            $browserInfo = 'Chrome';
        }
        elseif (strpos($_SERVER['HTTP_USER_AGENT'], 'Firefox'))
        {
            $browserInfo = 'Firefox';
        }
        else
        {
            $browserInfo = 'Default';
        }
        $IP = $_SERVER['REMOTE_ADDR'];

        News::create([
            'userName'      => $request['name'],
            'email'         => $request['email'],
            'homepage'      => $request['homepage'],
            'text'          => $request['text'],
            'browserInfo'   => $browserInfo,
            'IP'            => $IP,
        ]);

        return redirect()->route('news.index');
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //
    }

    public function getNews(Request $request, News $news)
    {
        $data = $news->getData();

        return \DataTables::of($data)
            ->addColumn('Created', function($data)
            {
                return  date($data->created_at);
            })
            ->make(true);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        //
    }
}

resources/views/user/news/create.blade.php
@extends('layouts.app')

@section('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card" style="margin-top: 20px;">
                    <h2 class="card-header bg-secondary text-white">Add New News</h2>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12 margin-tb">
                                <div class="pull-right">
                                    <a class="btn btn-primary" href="{{ route('news.index') }}"> Back</a>
                                </div>
                            </div>
                        </div>
                        <form action="{{ route('news.store') }}" method="POST">
                            @csrf
                            <div class="row" style="padding-left:8px;padding-right:8px;"  } >
                                {{-- Name field --}}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Name:</strong>
                                    <input type="text" name="name" maxlength="250" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                           value="{{ old('name') }}" placeholder="Name" autofocus>
                                    @if($errors->has('name'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Email:</strong>
                                    <input type="email" name="email" maxlength="250" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                                           value="{{ old('email') }}" placeholder="Email" autofocus>
                                    @if($errors->has('email'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Home Page:</strong>
                                    <input type="text" name="homePage" maxlength="250" class="form-control {{ $errors->has('homePage') ? 'is-invalid' : '' }}"
                                           value="{{ old('homePage') }}" placeholder="Home Page" autofocus>
                                    @if($errors->has('homePage'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('homePage') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Text:</strong>
                                    <textarea name="text" id="exampleFormControlTextarea" rows="5" class="form-control {{ $errors->has('text') ? 'is-invalid' : '' }}"
                                              value="{{ old('text') }}" placeholder="Text" autofocus></textarea>
                                    @if($errors->has('text'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('text') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="row" style="padding-left:8px;padding-right:8px;margin-top: 20px;"  } >
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/news/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>News</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
<!-- Right Side Of Navbar -->
<ul class="navbar-nav ml-auto">
    <!-- Authentication Links -->
    @guest
        @if (Route::has('login'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ ('Login') }}</a>
            </li>
        @endif

        @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ ('Register') }}</a>
            </li>
        @endif
    @else
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }}
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
    @endguest
</ul>
<div class="col-lg-12 margin-tb">
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('news.create') }}"> New News </a>
    </div>
</div>
<div class="container mt-5">
    <h1 class="mb-4 text-center">News</h1>
    <table class="table table-bordered yajra-datatable">
        <thead>
        <tr>
            <th>Created</th>
            <th>Name</th>
            <th>Email</th>
            <th>Text</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(function () {

        var table = $('.yajra-datatable').DataTable({
            processing: true,
            serverSide: true,
            pageLength: 25,
            ajax: '{{ route('get-news') }}',
            "order": [[ 0, "desc" ]],
            columns: [
                {data: 'Created', name: 'Created'},
                {data: 'userName', name: 'Name'},
                {data: 'email', name: 'Email'},
                {data: 'text', name: 'Text'},
            ]
        });

    });
</script>
</html>