routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\NewsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin','App\Http\Controllers\AdminController@index');

Auth::routes(['register' => false]);
//Auth::routes();

Route::resource('news', NewsController::class);

Route::resource('articles', ArticleController::class);
// Route for get articles for yajra post request.
Route::get('get-articles', [ArticleController::class, 'getArticles'])->name('get-articles');
Route::get('get-news', [NewsController::class, 'getNews'])->name('get-news');

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('articles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Get the data for listing in yajra.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function getArticles(Request $request, News $news)
    {
        $data = $news->getData();

        return \DataTables::of($data)
            ->addColumn('Actions', function($data) {
                    return '<button type="button" class="btn btn-primary btn-sm" id="getEditNewsData" data-id="'.$data->id.'"><i class="fas fa-edit"></i></button>
                    <button type="button" data-id="'.$data->id.'" data-toggle="modal" data-target="#DeleteNewsModal" class="btn btn-danger btn-sm" id="getDeleteId"><i class="fas fa-trash-alt"></i></button>';

            })
            ->rawColumns(['Actions'])

            ->addColumn('Created', function($data)
            {
                return  date($data->created_at);
            })

            ->make(true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required',
            'text'  => 'required',
        ]);

        $request['homepage'] = isset( $request['homepage']) ? $request['homepage'] : " ";

        if (strpos($_SERVER['HTTP_USER_AGENT'], 'Chrome'))
        {
            $browserInfo = 'Chrome';
        }
        elseif (strpos($_SERVER['HTTP_USER_AGENT'], 'Firefox'))
        {
            $browserInfo = 'Firefox';
        }
        else
        {
            $browserInfo = 'Default';
        }
        $IP = $_SERVER['REMOTE_ADDR'];

        News::create([
            'userName'      => $request['name'],
            'email'         => $request['email'],
            'homepage'      => $request['homepage'],
            'text'          => $request['text'],
            'browserInfo'   => $browserInfo,
            'IP'            => $IP,
        ]);

        return redirect()->route('articles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news, $id)
    {
        $news = News::find($id);
        return view('articles.edit',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required',
            'text'  => 'required',
        ]);

        $news = News::find($id);
        $news->update([
            'userName'      => $request['name'],
            'email'         => $request['email'],
            'text'          => $request['text'],
        ]);

        return redirect()->route('articles.index')
            ->with('success','News updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = new News;
        $news->find($id)->delete();

        return response()->json(['success'=>'News deleted successfully']);
    }
}

resources/views/articles/create.blade.php
@extends('adminlte::page')

@section('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card" style="margin-top: 20px;">
                    <h2 class="card-header bg-secondary text-white">Add New News</h2>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12 margin-tb">
                                <div class="pull-right">
                                    <a class="btn btn-primary" href="{{ route('articles.index') }}"> Back</a>
                                </div>
                            </div>
                        </div>
                        <form action="{{ route('articles.store') }}" method="POST">
                            @csrf
                            <div class="row" style="padding-left:8px;padding-right:8px;"  } >
                                {{-- Name field --}}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Name:</strong>
                                    <input type="text" name="name" maxlength="250" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                           value="{{ old('name') }}" placeholder="Name" autofocus>
                                    @if($errors->has('name'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Email:</strong>
                                    <input type="email" name="email" maxlength="250" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                                           value="{{ old('email') }}" placeholder="Email" autofocus>
                                    @if($errors->has('email'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Home Page:</strong>
                                    <input type="text" name="homePage" maxlength="250" class="form-control {{ $errors->has('homePage') ? 'is-invalid' : '' }}"
                                           value="{{ old('homePage') }}" placeholder="Home Page" autofocus>
                                    @if($errors->has('homePage'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('homePage') }}</strong>
                                        </div>
                                    @endif
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <strong>Text:</strong>
                                    <textarea name="text" id="exampleFormControlTextarea" rows="5" class="form-control {{ $errors->has('text') ? 'is-invalid' : '' }}"
                                              value="{{ old('text') }}" placeholder="Text" autofocus></textarea>
                                    @if($errors->has('text'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('text') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="row" style="padding-left:8px;padding-right:8px;margin-top: 20px;"  } >
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/articles/edit.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h2 class="card-header bg-secondary text-white">Edit News</h2>
                <div class="card-body">    
                    <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('articles.index') }}"> Back</a>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route('articles.update',$news->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                         <div class="row">
                            {{-- Name field --}}
                            <div class="col-xs-12 col-sm-12 col-md-12"> 
                                <strong>Name:</strong>
                                <input type="text" name="name" maxlength="250" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                       value="{{ old('name') == "" ? $news->userName : old('name') }}" placeholder="Name" autofocus>
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div> 
                            {{-- Email field --}}
                             <div class="col-xs-12 col-sm-12 col-md-12"> 
                                <strong>Email:</strong>
                                <input type="email" name="email" maxlength="250" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                                       value="{{ old('email') == "" ? $news->email : old('email') }}" placeholder="Email">
                                @if($errors->has('email'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                @endif
                            </div>

                            {{-- text field --}}
                            <div class="col-xs-12 col-sm-12 col-md-12"> 
                                <strong>Text:</strong>
                                <textarea type="text" name="text" rows="5" maxlength="250" class="form-control {{ $errors->has('text') ? 'is-invalid' : '' }}"
                                    placeholder="Text">{{ old('text') == "" ? $news->text : old('text') }}</textarea>
                                @if($errors->has('text'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('text') }}</strong>
                                    </div>
                                @endif
                            </div>

                       </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                              <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>    
@endsection

resources/views/articles/index.blade.php
@extends('adminlte::page')

@section('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <h5 class="card-header bg-secondary text-white">News</h5>
                    <div class="card-body">
                        <div class="pull-right"  >
                            <a class="btn btn-success" href="{{ route('articles.create') }}"> <i class="fas fa-plus"></i> Create New News</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered datatable">
                                <thead>
                                    <tr>
                                        <th>Created</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Text</th>
                                        <th width="150" class="text-center">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 <!-- Delete News Modal -->
<div class="modal" id="DeleteNewsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">News Delet</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <h4>Are you sure want to delete this News?</h4>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="SubmitDeleteNewsForm">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            // init datatable.
            var dataTable = $('.datatable').DataTable({
                processing: true,
                serverSide: true,
                autoWidth: false,
                pageLength: 10,
                // scrollX: true,
                "order": [[ 0, "desc" ]],
                ajax: '{{ route('get-articles') }}',
                columns: [
                    {data: 'Created', name: 'Created'},
                    {data: 'userName', name: 'Name'},
                    {data: 'email', name: 'Email'},
                    {data: 'text', name: 'Text'},
                    {data: 'Actions', name: 'Actions',orderable:false,serachable:false,sClass:'text-center'},
                ]
            });

             // Get single user in EditModel
            $('.modelClose').on('click', function(){
                $('#EditUserModal').hide();
            });
            var id;
            $('body').on('click', '#getEditNewsData', function(e) {
                // e.preventDefault();
                $('.alert-danger').html('');
                $('.alert-danger').hide();
                id = $(this).data('id');
                document.location.href = "articles/"+id+"/edit";
            });

            // Delete News Ajax request.
            var deleteID;
            $('body').on('click', '#getDeleteId', function(){
                deleteID = $(this).data('id');
            })
            $('#SubmitDeleteNewsForm').click(function(e) {
                e.preventDefault();
                var id = deleteID;
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: "articles/"+id,
                    method: 'DELETE',
                    success: function(result) {
                        document.location.href = "articles";
                    }
                });
            });
        });
    </script>
@endsection